stages:
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - echo "Setting up environment..."


# Jobs for each branch
.job_template:
  variables:  
    LANGUAGE: npm
    TYPE: vm
    PROJECT_NAME: ${CI_PROJECT_NAME}
    BUILD_NAME: ${CI_CONCURRENT_ID}
    WORKDIR: ${CI_PROJECT_DIR} 
  script:
    - echo "Running deployment script for branch ${CI_COMMIT_REF_NAME}..."
    - task ci:flow


# Pipeline for branches
deploy_branch:
  extends: .job_template
  stage: deploy
  only:
    - develop
  tags:
    - develop

deploy_release:
  extends: .job_template
  stage: deploy
  only:
    - release
  tags:
    - release

deploy_main:
  extends: .job_template
  stage: deploy
  only:
    - main
  tags:
    - main
