on:
  push:
    branches:
      - develop
      - release
      - main

env:
  environment: ''

jobs:
  deploy_flow:
    runs-on: self-hosted
    name: deploy flow

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set Environment
      run: |
        if [[ $GITHUB_REF == *hml* ]]; then
          echo "environment=homologation" >> $GITHUB_ENV
        elif [[ $GITHUB_REF == *main* ]]; then
          echo "environment=production" >> $GITHUB_ENV
        else
          echo "environment=develop" >> $GITHUB_ENV
        fi

    - name: Deployment
      run: bash task ci:flow
      env:
        LANGUAGE: npm
        TYPE: vm
        BUILD_NAME: ${{ github.run_id }}
        PROJECT_NAME: ${{ github.repository }}
        WORKDIR: ${{ github.workspace }}
        ENVIRONMENT: ${{ env.environment }}